USE [master]
GO
/****** Object:  Database [AQUA_Lakes]    Script Date: 27.6.2021 г. 23:18:12 ******/
CREATE DATABASE [AQUA_Lakes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AQUA_Lakes', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AQUA_Lakes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AQUA_Lakes_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AQUA_Lakes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AQUA_Lakes] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AQUA_Lakes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AQUA_Lakes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET ARITHABORT OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AQUA_Lakes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AQUA_Lakes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AQUA_Lakes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AQUA_Lakes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AQUA_Lakes] SET  MULTI_USER 
GO
ALTER DATABASE [AQUA_Lakes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AQUA_Lakes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AQUA_Lakes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AQUA_Lakes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AQUA_Lakes] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AQUA_Lakes] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AQUA_Lakes] SET QUERY_STORE = OFF
GO
USE [AQUA_Lakes]
GO
/****** Object:  Table [dbo].[Lakes]    Script Date: 27.6.2021 г. 23:18:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lakes](
	[Id] [int] NOT NULL,
	[LakeName] [nvarchar](50) NOT NULL,
	[Mountain] [nvarchar](50) NOT NULL,
	[BeginRiver] [nvarchar](50) NOT NULL,
	[Valley] [nvarchar](50) NOT NULL,
	[Altitude] [int] NOT NULL,
	[Area] [float] NOT NULL,
	[Volume] [float] NULL,
	[MaxDepth] [float] NULL,
 CONSTRAINT [PK_Lakes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [AQUA_Lakes] SET  READ_WRITE 
GO
